[pagar]
path = /srv/clients/pagar
browseable = yes
writable = yes
valid users = @grp_pagar
force group = grp_pagar
create mask = 0660
directory mask = 0770
write list = pagar_juhataja
veto files = /private_docs/ /admin_logs/

[auto]
path = /srv/clients/auto
browseable = yes
writable = yes
valid users = @grp_auto
force group = grp_auto
create mask = 0660
directory mask = 0770
write list = auto_juhataja
veto files = /private_docs/ /admin_logs/

[advokaat]
path = /srv/clients/advokaat
browseable = yes
writable = yes
valid users = @grp_advokaat
force group = grp_advokaat
create mask = 0660
directory mask = 0770
write list = advokaat_juhataja
veto files = /private_docs/ /admin_logs/
